#!/bin/bash
set -e

# Bootstrap Terraform Remote State Infrastructure
# This creates the S3 bucket and DynamoDB table for remote state

echo "🔧 Bootstrapping Terraform Remote State Infrastructure..."
echo ""

# Check for required variables
if [ -z "$TF_VAR_state_bucket_name" ] && [ ! -f "terraform.tfvars" ]; then
  echo "❌ Error: state_bucket_name is required"
  echo ""
  echo "Option 1: Set environment variable:"
  echo "  export TF_VAR_state_bucket_name=\"your-unique-bucket-name\""
  echo ""
  echo "Option 2: Create terraform.tfvars:"
  echo "  cp terraform.tfvars.example terraform.tfvars"
  echo "  # Edit terraform.tfvars and set state_bucket_name"
  echo ""
  exit 1
fi

# Set defaults from environment
export TF_VAR_aws_region="${TF_VAR_aws_region:-us-east-1}"
export TF_VAR_aws_profile="${TF_VAR_aws_profile:-}"

echo "📦 Initializing Terraform..."
terraform init

echo "✅ Validating configuration..."
terraform validate

echo "📋 Planning bootstrap deployment..."
terraform plan -out=tfplan

echo ""
read -p "Deploy bootstrap infrastructure? (yes/no): " confirm
if [ "$confirm" = "yes" ]; then
  echo "🔧 Applying bootstrap..."
  terraform apply tfplan
  
  echo ""
  echo "✅ Bootstrap complete!"
  echo ""
  
  # Get outputs
  BUCKET_NAME=$(terraform output -raw state_bucket_name)
  TABLE_NAME=$(terraform output -raw lock_table_name)
  REGION="${TF_VAR_aws_region}"
  
  # Create backend.hcl in the main terraform directory
  BACKEND_FILE="../terraform/backend.hcl"
  
  echo "📝 Creating backend configuration..."
  cat > "$BACKEND_FILE" <<EOF
# Backend configuration for Terraform remote state
# Generated by bootstrap script on $(date)

bucket         = "$BUCKET_NAME"
key            = "pr-reminder-bot/terraform.tfstate"
region         = "$REGION"
dynamodb_table = "$TABLE_NAME"
encrypt        = true
EOF
  
  echo "✅ Created $BACKEND_FILE"
  echo ""
  echo "📍 Backend Configuration:"
  echo "  Bucket: $BUCKET_NAME"
  echo "  Region: $REGION"
  echo "  Lock Table: $TABLE_NAME"
  echo ""
  echo "🎯 Next Steps:"
  echo "  1. cd ../terraform"
  echo "  2. terraform init -backend-config=backend.hcl -reconfigure"
  echo "  3. terraform apply"
  echo ""
  
else
  echo "❌ Bootstrap cancelled"
  rm -f tfplan
  exit 1
fi
